#!/usr/bin/env bash
# Script that displays numbers from 1-100, displays "FizzBuzz" for multiple of 3 & 5
# displays "Fizz" for multiple of 3 and displays "Buzz" for multiple of 5 else display number in list format
for x in {1..100}
do
    if [[ $((x % 5)) -eq 0 && $((x % 3)) -eq 0 ]]; then
        echo "FizzBuzz"
    elif [ $((x % 3)) -eq 0 ];then
        echo "Fizz"
    elif [ $((x % 5)) -eq 0 ];then
        echo "Buzz"
    else
        echo $x
    fi
done