#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, at 9 say "Hi"
x=0
while [ $x -le 12 ]
do
    y=1
    echo "Hour:" $x
    while [ $y -le 59 ]
    do
        echo $y
        y=$((y+1))
    done
    x=$((x+1))
done